version: "3.7"

services:

  pihole:
    container_name: pihole
    domainname: ${DOMAIN}
    image: pihole/pihole:v4.4_amd64
    restart: always
    ports:
      - target: 53
        published: 53
        mode: host
      - target: 67
        published: 67
        protocol: udp
        mode: host
    healthcheck:
      test: ["CMD", "dig", "+norecurse", "+retry=0", "@127.0.0.1", "pi.hole"]
      interval: 1m30s
      timeout: 10s
      retries: 10
      start_period: 40s
    environment:
      ServerIP: ${SERVERIP}
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${WEBPASSWORD}
      DNS1: 1.1.1.2
      DNS2: 1.0.0.2
      VIRTUAL_HOST: pihole.${DOMAIN}
      VIRTUAL_PORT: 80
      DNSMASQ_LISTENING: all
      DNSSEC: "true"
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    networks:
      - traefik-public
      - pihole-network
    dns:
      - 127.0.0.1  # Sets your container's resolve settings to localhost so it can resolve DHCP hostnames from Pi-hole's DNSMasq, also fixes common resolution errors on container restart.
      - 1.1.1.2  # Sets a backup server of your choosing in case DNSMasq has problems starting
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.lan-dns == True
      labels:
        - traefik.enable=true
        - traefik.frontend.rule=Host:pihole.${DOMAIN?Variable DOMAIN not set}
        - traefik.port=80
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https
    configs:
      - source: pihole_lanlist
        target: /etc/pihole/lan.list
      - source: pihole_lanconf
        target: /etc/dnsmasq.d/02-lan.conf

configs:
  pihole_lanlist:
    file: ./secrets/lan.list
  pihole_lanconf:
    file: ./configs/02-lan.conf

volumes:
  pihole:
  dnsmasq:

networks:
  traefik-public:
    external: true
  pihole-network:
    external: true
