---

- name: Set swarm labels
  hosts: managers[0]
  vars_files:
    - vars/main.yml
  tasks:
    - name: Get info on all nodes
      docker_node_info:
      register: result
    - name: Add labels to nodes
      docker_node:
        hostname: "{{ item.Description.Hostname }}"
        labels: "{{ hostvars[item.Description.Hostname]['swarm_labels'] |default({}) }}"
      loop: "{{ result['nodes'] }}"
  tags: labels

- name: Deploy pihole
  hosts: managers[0]
  vars_files:
    - vars/main.yml
  tasks:
    - name: Disable the resolved service
      systemd:
        state: stopped
        enabled: no
        name: systemd-resolved
      when: swarm_labels['lan-dns'] is defined and swarm_labels['lan-dns'] == 'true'

    - name: update resolv.conf
      lineinfile:
        path: '/etc/resolv.conf'
        state: present
        regexp: '^nameserver '
        line: 'nameserver 1.1.1.2'
      when: swarm_labels['lan-dns'] is defined and swarm_labels['lan-dns'] == 'true'

    - name: Create network for other services to access the lan dns service
      docker_network:
        state: present
        name: pihole-network
        scope: swarm
        driver: overlay
        attachable: yes
      when: swarm_labels['lan-dns'] is defined and swarm_labels['lan-dns'] == 'true'

    - file: state=directory path=/opt/stacks/pihole/configs
      when: swarm_labels['lan-dns'] is defined and swarm_labels['lan-dns'] == 'true'
    - file: state=directory path=/opt/stacks/pihole/secrets
      when: swarm_labels['lan-dns'] is defined and swarm_labels['lan-dns'] == 'true'

    - copy:
        src: configs/02-lan.conf
        dest: /opt/stacks/pihole/configs/02-lan.conf
      when: swarm_labels['lan-dns'] is defined and swarm_labels['lan-dns'] == 'true'
    - copy:
        src: secrets/lan.list
        dest: /opt/stacks/pihole/secrets/lan.list
      when: swarm_labels['lan-dns'] is defined and swarm_labels['lan-dns'] == 'true'

    - copy:
        src: pihole.stack.yml
        dest: /opt/stacks/pihole/docker-compose.yml
      when: swarm_labels['lan-dns'] is defined and swarm_labels['lan-dns'] == 'true'
    - docker_stack:
        state: present
        name: pihole
        compose:
          - /opt/stacks/pihole/docker-compose.yml
      environment:
        DOMAIN: "apps.{{ domain }}"
        WEBPASSWORD: "{{ admin_password }}"
        SERVERIP: "{{ hostvars[inventory_hostname]['ansible_' + lan_interface]['ipv4']['address'] }}"
        TIMEZONE: "Europe/Amsterdam"
      when: swarm_labels['lan-dns'] is defined and swarm_labels['lan-dns'] == 'true'
  tags: pihole

- name: Deploy vpn
  hosts: managers[0]
  tasks:
    - file: state=directory path=/opt/stacks/vpn/secrets

    - copy:
        src: secrets/vpn.env
        dest: /opt/stacks/vpn/secrets/vpn.env

    - copy:
        src: vpn.compose.yml
        dest: /opt/stacks/vpn/docker-compose.yml
    - shell:
        cmd: docker-compose --project-name lan --file docker-compose.yml up -d
        chdir: /opt/stacks/vpn
  tags: vpn

- name: Deploy resilio-sync
  hosts: managers[0]
  vars_files:
    - vars/main.yml
  tasks:

    - name: Create an empty file to store the first deployment timestamp
      copy:
        content: ""
        dest: "/opt/hello"
        force: no
    - name: Get the first deployment timestamp
      shell: "stat --format '%Y' /opt/hello"
      register: filetime_result
    - name: Do ssh keyscan on ansible host
      shell: "cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-keygen -l -f - | grep ED25519"
      register: keyscan_result
      until: keyscan_result.rc == 0
      retries: 10
      delay: 60
    - name: Set fingerprint for ansible host
      set_fact:
        fingerprint: "{{ keyscan_result.stdout.split(' ')[1] }}"
    - name: Create admin password hash for stack
      set_fact:
        admin_password_salt: "{{ ['resilio', fingerprint, filetime_result.stdout] | join('|') | hash('sha1') | truncate(16, True, '') }}"
    - name: Create admin password hash for stack
      set_fact:
        admin_password_hash: "{{ admin_password | password_hash('sha512', rounds=999999, salt=admin_password_salt) }}"

    - file: state=directory path=/opt/stacks/resilio/configs
    - file: state=directory path=/opt/stacks/resilio/secrets
    - file: state=directory path=/mnt/storage/sync

    - copy:
        src: secrets/Sync_Pro_License.btskey
        dest: /opt/stacks/resilio/secrets/Sync_Pro_License.btskey
    - template:
        src: configs/sync.conf.j2
        dest: /opt/stacks/resilio/configs/sync.conf

    - copy:
        src: resilio-sync.stack.yml
        dest: /opt/stacks/resilio/docker-compose.yml
    - docker_stack:
        state: present
        name: resilio
        compose:
          - /opt/stacks/resilio/docker-compose.yml
      environment:
        DOMAIN: "apps.{{ domain }}"
  tags: resilio

- name: Deploy timemachine
  hosts: managers[0]
  vars_files:
    - vars/main.yml
  tasks:
    - file: state=directory path=/opt/stacks/timemachine/secrets
    - file: state=directory path=/opt/stacks/timemachine/configs/users
    - file: state=directory path=/mnt/storage/timemachine

    - template:
        src: configs/timemachine-user.conf.j2
        dest: "/opt/stacks/timemachine/configs/users/{{ create_user }}.conf"
    - copy:
        src: timemachine.stack.yml
        dest: /opt/stacks/timemachine/docker-compose.yml

    - docker_stack:
        state: present
        name: timemachine
        compose:
          - /opt/stacks/timemachine/docker-compose.yml
  tags: timemachine
