version: "3.3"

services:
  vpn:
    image: hwdsl2/ipsec-vpn-server
    restart: always
    env_file:
      - ./secrets/vpn.env
    ports:
      - target: 500
        published: 500
        protocol: udp
        mode: host
      - target: 4500
        published: 4500
        protocol: udp
        mode: host
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
    networks:
      - pihole-network
#    dns:
#      - pihole
#      - 1.1.1.2

networks:
  pihole-network:
    external: true
